services:
  documentdb:
    image: 'ghcr.io/microsoft/documentdb/documentdb-local:latest'
    environment:
      - 'USERNAME=fiap'
      - 'PASSWORD=fiap'
      - 'DATA_PATH=/data'
    ports:
      - '10260:10260'
    volumes:
      - documentdb_data:/data
volumes:
  documentdb_data:
