services:
  app:
    build: . # Constrói a imagem a partir do Dockerfile neste diretório
    ports:
      - "8080:8080" # Mapeia a porta da aplicação para o seu host
    environment:
      # A CHAVE: Mudar localhost para o NOME DO SERVIÇO (documentdb)
      # Aqui você usa a string de conexão que funcionou no mongosh
      - SPRING_DATA_MONGODB_URI=mongodb://fiap:fiappostech@docdb-2025-11-04-12-13-04.cluster-cxemcy4amni1.us-east-2.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
    restart: always
