name: SonarCloud Scan (Maven, Java 21)

on:
  push:
    branches: ["main", "master", "feature/apenasPessoas"]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  YOUR_PROJECT_KEY: thiagolinoz_FastFoodPessoas
  YOUR_SONARCLOUD_ORGANIZATION: thiagolinoz
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 and cache Maven deps
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build and analyze with Maven
        run: |
          mvn -B -DskipTests=false verify jacoco:report sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.projectKey=${{ env.YOUR_PROJECT_KEY }} \
            -Dsonar.organization=${{ env.YOUR_SONARCLOUD_ORGANIZATION }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml,target/site/jacoco/jacoco.xml
